### ISSUE TITLE
Releases on github and docker hub

### ISSUE THREAD

**Issue by Steniaz** [evry/docker-oidc-proxy#1]
Hey,

I used this repo to successfully place a proxy in of the kubernetes dashboard. I only have one little problem. At this moment this repo does not have "official" releases or versions. The image deployed on docker hub is tagged as latest. I would like for it to have a version number so I can use without worrying that a new version will break my setup.

Stijn De Haes

**Comment by Starefossen** [comment]
Thanks for the feedback @Steniaz 👍🏼 I'll make a new release procedure which involves tagging in git and on Docker Hub!

**Comment by Steniaz** [comment]
@Starefossen Thank you for the quick answer :) and thank you for doing it!

**Comment by Starefossen** [comment]
Just built and and tagged v1.0.0 on Docker Hub and git. I would love to hear your experience using this image, and as always, any contributions are more than welcome 🎉 😄
